language: python
fast_finish: true

os:
  - linux

python:
  - 3.6

group: travis_latest

git:
  depth: 3


install:
  - pip -q install -e .[tests,io]

script: 
  - pytest -v
  - flake8
  - mypy . --ignore-missing-imports

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
    pytest --cov;
    coveralls;
    fi

